### ISSUE TITLE
Get-PASuser doesn't work with -username parameter

### ISSUE THREAD

**Issue by arkayali** [pspete/psPAS#409] opened 2022-08-15 17:18 UTC
**Describe the issue**
The cmdlet returns an error when I run it with -username with/without -UseGen1API

**To Reproduce**
Get-PASUser -username safeowner 
returns: minimum version of 12.2 

Get-PASUser -username safeowner -UseGen1API
returns: error 404

**Expected behavior**
get details on the requested user

**Screenshots & Console Output**

![image](https://user-images.githubusercontent.com/44178884/184683759-a0f40375-4f68-474c-93d6-ec89537c020a.png)

**Your Environment**
Include relevant details about your environment

PowerShell Version: 5
psPAS Version: 5.3.69
CyberArk Version: 11.5

**Additional context**

**Comment by pspete** [comment] 2022-08-15 19:07
The project does not have a compatible environment available to test/validate the Gen1 API call... It's been depreciated in recent versions.
 
See the command Syntax here: https://pspas.pspete.dev/commands/Get-PASUser#gen2-default
Every other Gen 2 parameter other than `UserName` should be available to you.

**Comment by pspete** [comment] 2022-08-17 00:24
Now resolved in 5.3.76, and tested with 11.5
This was caused by a URL format change introduced for some Gen1 commands in the last release (5.3.69), now reverted.

**Closed by pspete** 2022-08-17 00:24 UTC
