### ISSUE TITLE
SAML Integration from PS-SAML-Interactive.psm1 with module psPAS v 4.5.90. and Azure SSO

### ISSUE THREAD

**Issue by grvs1404** [pspete/psPAS#418] opened 2022-08-22 20:07 UTC
Hello, 
I am attempting to use the SAML Integration from PS-SAML-Interactive.psm1 with your module psPAS v 4.5.90.
We are on Cyberark version 11.4 which in lies the compatibility with v 4.5.90.

I believe this is more on the @allynl93 side of the track but I was unable to create an issue on his project. Hoping as he is listed as a contributor he may be able to see it here.

The $LoginURL Below is coming specifically from Azure Enterprise Application configured for this SSO

When running the script below
```
Where $BaseURL is our CyberArk Portal
$loginURL = "https://login.microsoftonline.com/********-****-****-****-************/saml2"
$loginResponse = New-SAMLInteractive -LoginIDP $loginURL
New-PASSession -BaseURI $baseURL -SAMLAuth -SAMLResponse $loginResponse
```

I am getting a popup that doesn't let me get my login/SAMLResponse.
![image](https://user-images.githubusercontent.com/65643867/186006890-b28fd58b-4226-40ae-b423-942dac04b7b5.png)

When I use the $loginURL with my SAMLResponse already present the New-PASSession works successfully.
![image](https://user-images.githubusercontent.com/65643867/186008678-97e574c2-5556-4359-a64d-9baa5a3a6499.png)

PS Version - 5.1
psPAS - 4.5.90
CyberArk - 11.4

I apologize if I have left anything out this is my first time opening an issue. Ive also scowered the web and so far I'm unable to find a similar issue that involves Azure SSO.

**Comment by allynl93** [comment] 2022-08-23 09:42
Sorry, I hadn't realised issues weren't enabled on my repo. I've enabled that now.

The issue is because you are using the SP initiated URL. For this integration to work, at least so far, you need to use an IDP initiated logon.

- First step is to enable IDP initiated sign in on your PVWA(s). According to the 11.4 documentation this is supported. See the note section in: https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/11.4/en/Content/PAS%20INST/SAML-Authentication.htm

- Your $loginURL needs to be the user access URL rather than the SAML login URL. You can grab this from the properties tab for the enterprise app. Typically starts with https://myapps.microsoft.com.

I hope this helps. 

Thanks
Allyn

**Comment by pspete** [comment] 2022-08-23 10:07
Thanks for the input on this @allynl93 👍🏼 

@grvs1404 
> We are on Cyberark version 11.4 which in lies the compatibility with v 4.5.90.

psPAS versions contain support for API features released in specific CyberArk versions **_and_** general fixes or updates to module code; any recent psPAS versions should have backward compatibility with historic CyberArk versions all the way back to version 9.  

Some updates specifically relating to the `SAMLResponse` parameter of `New-PASSession` were included in v5.1.16 - see the release notes here: https://github.com/pspete/psPAS/blob/master/CHANGELOG.md#5116-may-23rd-2021

With CyberArk version `11.4`, there should be no reason preventing use of the latest psPAS version (though check the release notes for details of any introduced breaking changes :smile:)

**Comment by grvs1404** [comment] 2022-08-23 18:17
Hey Allyn,
Thank you sir, Im pretty sure I did check the IDP initiated sign on  ... Nope it was not update like i thought it was. I have modified that and let you know if that fixes it.

Hey Pete,
I did actually attempt to use the newest version of psPAS. Two of our employees wrote a complex script that adds new users, safes and modifies the safe permissions. I believe the safe aspect of the script broke when we upgraded. Until we finally upgrade to 12.x we are stuck at using 4.5.90.

**Comment by pspete** [comment] 2022-08-24 10:24
> I believe the safe aspect of the script broke when we upgraded

Module updates for safe management features have been added in recent versions to reflect API updates in the product. 

For existing/working scripts it makes sense to ensure they use an intended version of the module.

If you do need to use an updated version of the module, and new paramtersets for new API capabilities have been added to the psPAS commands being used, updates to the scripts may be required to make sure the correct paramterset is being used.
Often as simple as adding the `-useGen1API` switch where it is available.

All breaking changes between module versions are detailed in the changelog, and all module documentation reflects the usage for the latest module versions.

**Comment by grvs1404** [comment] 2022-08-24 12:58
Interesting, I will have to look into that!

**Comment by grvs1404** [comment] 2022-08-25 19:49
I resolved the issues with my internet connection and while attempting to use  the following commands I got:
```
$loginURL = 'https://myapps.microsoft.com/signin/****'
$baseURL = 'https://FQDN'
```
 and running 

`$loginResponse = New-SAMLInteractive -LoginIDP $loginURL`
Received the following
![image](https://user-images.githubusercontent.com/65643867/186752201-4257fdc6-78e1-4dd3-b8a0-436969e4e81c.png)
If i click refresh the page it is complaining about TLS or Cipher
![image](https://user-images.githubusercontent.com/65643867/186752839-972c1e45-cc5b-4892-89c9-cb7aa8dc7d7e.png)

I tried adding all of the TLS options to no avail
Is saml allowed to be used even if you dont use the New-SAMLInteractive command?

**Comment by pspete** [comment] 2022-09-01 20:08
> My Next question or issue is using -usegen1api. When using this with `get-passafe -usegen1api` and tried using an * with `-safename` and without. it doesnt return anything but should return all safes.

That's an odd one @grvs1404 - no answer for why that might be right now. The wildcard should not be needed.
Something like the below would get you the safe list from that API:

```powershell
$ws = Get-PASSession
$url = "$($ws.BaseURI)/WebServices/PIMServices.svc/Safes"
Invoke-RestMethod -Method GET -Uri $url -WebSession $($ws.WebSession) -ContentType "application/json"
```
I think [`Find-PASSafe`](https://pspas.pspete.dev/commands/Find-PASSafe) was found to be the quickest way to get all safe names for versions prior to 11.7....

**Comment by pspete** [comment] 2022-09-01 20:44
re-reading the input provided into this issue - as you're using psPAS 4.5.90 - `Get-PASSafe` has no `-useGen1API` switch.....
from psPAS version 5.0, the command to get all safes using the gen1API would be
```powershell
Get-PASSafe -FindAll
```
As per [Example 5](https://pspas.pspete.dev/commands/Get-PASSafe#example-5) in the docs.

**Comment by grvs1404** [comment] 2022-09-01 21:06
Ahh ok, maybe i was confusing the two, I was having issues with Allyns module so I was trying to move to using solely PSPAS and just use the newest version. Is it possible to use Solely PSPAS with SAML? If not no big deal, I am not seeing a way to get the SAML response from the myapps website. With all that I was able to get logged on from 1 server in our environments and ran the commands one by one to validate our scripts will work using the -useGen1API.

**Comment by pspete** [comment] 2022-09-01 21:31
> Is it possible to use Solely PSPAS with SAML

Sure, either by providing a SAMLResponse, or SAML SSO using Windows Integrated Authentication like [Example 8](https://pspas.pspete.dev/commands/New-PASSession#example-8) - if your config & IDP support it... though YMMV.

I'd opt for Allyn's PS-SAML-Interactive module to get the SAMLResponse.

**Comment by pspete** [comment] 2022-09-10 22:24
Closing as not anything to fix in the psPAS code.
Comment if you feel this is not the case :)

**Closed by pspete** 2022-09-10 22:24 UTC

**Comment by grvs1404** [comment] 2022-09-13 13:30
Thanks Pete and Allyn great job on the modules!
