### ISSUE TITLE
Invalid URI: The hostname could not be parsed

### ISSUE THREAD

**Issue by santhakumar2619** [pspete/psPAS#264] opened 2020-04-28 10:39 UTC
## Your Environment

![Capture](https://user-images.githubusercontent.com/53302312/80477254-41660d80-8969-11ea-9fbf-2f79d1506ee8.PNG)

* PowerShell Version: 5.1
* psPAS Branch & Version: 3.5.8
* CyberArk Version: 11.1

## Expected Behaviour

New-PASSession should login the user using CyberArk Authentication

## Current Behaviour

New-PASSession is failing with the below error,

Invoke-PASRestMethod : Invalid URI: The hostname could not be parsed. Run New-PASSession

## Syntax

New-PASSession -Credential AdminUser -BaseURI https://pvwa

**Comment by pspete** [comment] 2020-04-28 12:25
The provided error message would usually be generated if a psPAS command is attempted to be run without a successful authentication first having taken place. 

Please provide the verbose & debug output for your command:

```powershell
$DebugPreference = "Continue"
New-PASSession -Credential AdminUser -BaseURI https://pvwa -verbose
```

**Comment by pspete** [comment] 2020-05-04 14:21
@santhakumar2619, can this issue be closed?
If you do still need help, the requested additional details must be provided.

**Comment by pspete** [comment] 2020-05-05 14:52
@santhakumar2619 leave a comment if you want this reopened.

**Comment by santhakumar2619** [comment] 2020-05-09 08:34
Hi Pete,

Sorry for the delay. Please open this issue.

I'm getting the below response after enabling debug.

![Capture1](https://user-images.githubusercontent.com/53302312/81468544-d7b5f100-91fd-11ea-8809-a462fe733c88.PNG)


Thanks,
Santha Kumar

**Comment by pspete** [comment] 2020-05-09 10:41
@santhakumar2619 - reopening as requested. 
The output you shared does not show the error you originally logged with the issue.
What has changed with the command you are using? 

It looks like an issue in your local environment and not with the psPAS module; the authentication request is being sent to the expected URL endpoint, but a zero byte response is received.

Unfortunately it is not something which can be reproduced:
![image](https://user-images.githubusercontent.com/10600090/81471524-91ef2d80-91e9-11ea-8c34-019e03492991.png)

**Comment by pspete** [comment] 2020-05-09 15:22
You could attempt an authentication outside of the module to confirm if it works for you or not:

```powershell
$url = "https://Your-PVWA/PasswordVault/api/Auth/Cyberark/Logon"
$body = New-Object -Property @{"username" = "Administrator"; "password" = "SomePassword" } -TypeName psobject | ConvertTo-Json

Invoke-RestMethod -Uri $url -Method POST -ContentType "application/json" -Body $body
```

**Comment by santhakumar2619** [comment] 2020-05-11 14:04
Pete.. 

I've created  Untitled.ps1 file adding the above commands and getting a null response for the Post method. 

PS C:\Users\myuser> C:\Users\myuser\Desktop\Untitled1.ps1


PS C:\Users\myuser>

**Comment by pspete** [comment] 2020-05-11 16:17
No API token response, or even a generic or a CyberArk error (E.G. "Authentication Failure"), suggests a fundamental issue which must be resolved.
As Authentication appears to not work for you outside of psPAS, there is no fix which can be applied to the module's code, hence closing.

**Closed by pspete** 2020-05-11 16:17 UTC
